version: '3'
services:
  labs64io:
    image: jekyll/jekyll:latest
    container_name: labs64.io
    volumes:
      - '.:/srv/jekyll'
    ports:
      - 4000:4000
    working_dir: /srv/jekyll
    command: 'jekyll serve --watch --incremental --verbose --drafts --future --config _config.yml,_config_dev.yml'
